# ExcelSaveFix.py
#
# just opens and saves an excel file to fix the
# problem with the autogenerated files built with
# xlwt.  Excel could not link to autogenerated files
# unless they were opened and saved in Excel.
#
# Written:         Mar 2011
# Release date:    Mar 2012
# Written by: Jeanne Jones, USGS, jmjones@usgs.gov
# 
# This software is in the public domain because it contains materials that 
# originally came from the United States Geological Survey, an agency of the 
# United States Department of Interior. For more information, see the official 
# USGS copyright policy at 
# http://www.usgs.gov/visual-id/credit_usgs.html#copyright

import os, sys, traceback
import win32com.client

def excelsave( gp, xlfile ):
    try:
        xl=win32com.client.Dispatch('Excel.Application') 
        srce=xl.Workbooks.Open( xlfile )
        srce.Save() 
        srce.Close()

    except Exception:
        tb = sys.exc_info()[2]
        tbinfo = traceback.format_tb(tb)[0]
        pymsg = tbinfo + "\n" + str(sys.exc_type)+ ": " + str(sys.exc_value)
        gp.AddMessage(pymsg)
